"""Base agent class for multi-agent reasoning."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class AgentOpinion:
    """Opinion generated by an agent."""
    agent_type: str
    recommendation: str  # "BUY", "HOLD", "SELL"
    confidence: float  # 0-1
    reasoning: str
    reasoning_path: dict = field(default_factory=dict)

    def __str__(self) -> str:
        return f"{self.agent_type}: {self.recommendation} (confidence: {self.confidence:.2f})\n{self.reasoning}"


class BaseAgent(ABC):
    """Abstract base class for specialized financial agents."""

    def __init__(self, agent_type: str):
        """Initialize agent.

        Args:
            agent_type: Type of agent (e.g., "Fundamental", "Sentiment")
        """
        self.agent_type = agent_type
        self.opinion_history: list[AgentOpinion] = []

    @abstractmethod
    def reason(self, context: str) -> AgentOpinion:
        """Generate initial opinion based on context.

        Args:
            context: Knowledge graph context formatted as string

        Returns:
            AgentOpinion with recommendation and reasoning
        """
        pass

    @abstractmethod
    def refine(
        self,
        current_opinion: AgentOpinion,
        peer_opinions: list[AgentOpinion]
    ) -> AgentOpinion:
        """Refine opinion based on peer opinions (debate mechanism).

        Args:
            current_opinion: Agent's current opinion
            peer_opinions: Opinions from other agents

        Returns:
            Refined AgentOpinion
        """
        pass

    def _mock_reasoning(
        self,
        context: str,
        focus_area: str,
        weights: dict[str, float]
    ) -> tuple[str, float, str]:
        """
        Mock reasoning logic (simulates LLM reasoning).

        Args:
            context: Knowledge graph context
            focus_area: What to focus on in analysis
            weights: Weights for decision factors

        Returns:
            Tuple of (recommendation, confidence, reasoning)
        """
        # Simple mock logic for demo
        # In production, this would call actual LLM
        recommendation = "HOLD"
        confidence = 0.5
        reasoning = f"Mock analysis focusing on {focus_area}"
        return recommendation, confidence, reasoning
